name: Sync Main Branches

on:
  push:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  # This workflow syncs master to docker branch
  merge_docker:
    name: Sync Docker Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Merge master -> docker
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git checkout docker
          git merge master --ff-only
          git push
  merge_github:
    name: Sync GitHub Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Merge master -> github
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git checkout github
          git merge master --ff-only
          git push
